/*
 * ============================================================================
 *  FujiNet config ROM -- embedded boot image (see fujinet_config_rom.c)
 * ============================================================================
 *  Generated by src/fujinet/mkconfigrom.py -- DO NOT HAND-EDIT.
 * ============================================================================
 */
#ifndef FUJINET_CONFIG_ROM_H_
#define FUJINET_CONFIG_ROM_H_

extern const unsigned char fujinet_config_rom[];
extern const long          fujinet_config_rom_len;

#endif /* FUJINET_CONFIG_ROM_H_ */
