#!/usr/bin/env python3
"""mkconfigrom.py -- pack fujinet-config/intv/config.rom into a C source
file (fujinet_config_rom.c) plus matching header (fujinet_config_rom.h),
so jzIntv can boot straight into the FujiNet config menu with no ROM file
on disk (`jzintv --fujinet` with no ROM argument).

config.rom is the Intellicart-format (self-describing, 0xA8-header) output
of `fujinet-config/intv`'s `as1600 -o config.rom config.asm` build step; it
carries its own memory mapping/attributes, so no sibling .cfg is needed --
icartrom_decode() handles it exactly like any other .rom file.

The array is emitted uncompressed (not via jzIntv's LZOE embed mechanism)
because LZOE compiles to a no-op under -DNO_LZO (see src/lzoe/lzoe.h), and
this feature should work on every build configuration.

Usage:
    mkconfigrom.py config.rom fujinet_config_rom.c fujinet_config_rom.h

Regenerate after rebuilding fujinet-config/intv/config.rom:
    cd fujinet-config/intv && make
    python3 src/fujinet/mkconfigrom.py \\
        ../../fujinet-config/intv/config.rom \\
        src/fujinet/fujinet_config_rom.c \\
        src/fujinet/fujinet_config_rom.h
(paths relative to the jzIntv source tree root)
"""
import sys
import time

C_HEADER = """/*
 * ============================================================================
 *  FujiNet config ROM -- embedded boot image
 * ============================================================================
 *  This is the Intellicart-format (.rom) build of fujinet-config/intv --
 *  the WiFi setup / host slots / directory browser / boot-a-ROM menu that
 *  a real FujiNet-for-Intellivision cartridge shows on power-up. It is
 *  embedded here so `jzintv --fujinet` with no ROM argument on the command
 *  line boots straight into it, the same way a real RP2040 FujiNet
 *  cartridge would, with no separate ROM file needed on disk.
 *
 *  Source: fujinet-config/intv/config.rom (a build artifact of the
 *  fujinet-config repository -- see fujinet-config/intv/Makefile). The
 *  .rom format is self-describing (Intellicart/CC3 header), so it carries
 *  its own memory mapping and needs no sibling .cfg file.
 *
 *  Generated by src/fujinet/mkconfigrom.py -- DO NOT HAND-EDIT.
 *  Regenerate with:
 *      cd fujinet-config/intv && make
 *      python3 src/fujinet/mkconfigrom.py \\
 *          <path-to>/fujinet-config/intv/config.rom \\
 *          src/fujinet/fujinet_config_rom.c \\
 *          src/fujinet/fujinet_config_rom.h
 *
 *  Generated: {gen_time}
 *  Source size: {size} bytes
 * ============================================================================
 */

#include "fujinet/fujinet_config_rom.h"

const long fujinet_config_rom_len = {size};

const unsigned char fujinet_config_rom[{size}] =
{{
"""

C_FOOTER = "};\n"

H_TEMPLATE = """/*
 * ============================================================================
 *  FujiNet config ROM -- embedded boot image (see fujinet_config_rom.c)
 * ============================================================================
 *  Generated by src/fujinet/mkconfigrom.py -- DO NOT HAND-EDIT.
 * ============================================================================
 */
#ifndef FUJINET_CONFIG_ROM_H_
#define FUJINET_CONFIG_ROM_H_

extern const unsigned char fujinet_config_rom[];
extern const long          fujinet_config_rom_len;

#endif /* FUJINET_CONFIG_ROM_H_ */
"""


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} config.rom out.c out.h", file=sys.stderr)
        return 1

    rom_path, c_path, h_path = sys.argv[1:4]

    with open(rom_path, "rb") as f:
        data = f.read()

    gen_time = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

    with open(c_path, "w") as f:
        f.write(C_HEADER.format(gen_time=gen_time, size=len(data)))
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write(C_FOOTER)

    with open(h_path, "w") as f:
        f.write(H_TEMPLATE)

    print(f"wrote {c_path} and {h_path} ({len(data)} bytes embedded)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
