##############################################################################
##  Termux no longer has its own Makefiles.  It uses the default Linux
##  Makefiles instead.
##
##  This Makefile includes a couple buildcfg/ files to tweak the default
##  Linux build for Termux.  If you wish, you can make symlinks in buildcfg/
##  and use Makefile.linux_sdl1 directly.
##
##  Run 'make symlink' to create the recommented symlinks in buildcfg/.
##
##  See buildcfg/README.txt for more information on how buildcfg/ works.
##############################################################################
include buildcfg/00-compiler-termux-clang.mak.txt
include buildcfg/80-x11-workarounds.mak.txt
include Makefile.linux_sdl1

symlink:
	cd buildcfg && (ln -s 00-compiler-termux-clang.mak.txt 00-compiler.mak || :)
	cd buildcfg && (ln -s 80-x11-workarounds.mak.txt 80-x11-workarounds.mak || :)
